### ISSUE TITLE
LRU semantics

### ISSUE THREAD

**Issue by stefanpenner** [stefanpenner/ember-state-services#3]
- [ ] limit
- [ ] `willDestroyState` /  `shouldDestroy` (allows to abort if needed, also promise interface)
- [ ] ... ?

**Comment by stefanpenner** [comment]
@thoov this may be of interest to you.

**Comment by thoov** [comment]
@stefanpenner: I'm trying to think of a case where you want to actually "destroy" state and not just "clear/reset" state. My issue if we allow a user to destroy the state backing a service then wont they get into weird states trying to set properties on a destroyed object?

**Comment by stefanpenner** [comment]
New approach doesn't really need this.
