### ISSUE TITLE
Add v2.0.0 tag

### ISSUE THREAD

**Issue by Serabe** [stefanpenner/ember-state-services#40]
Add v2.0.0 tag to the repo.

**Comment by thoov** [comment]
Thanks for bring this up!

**Comment by Serabe** [comment]
Thank you!

If you change the rag to v2.0.0 it will be shown the first one, which is pretty helpful to know the last version tagged.

**Comment by stefanpenner** [comment]
@thoov make sure to tag with a prefixed v

**Comment by thoov** [comment]
I update it

**Comment by mike-north** [comment]
Related: #61
