### ISSUE TITLE
Ember Data models don't work properly with weakmaps

### ISSUE THREAD

**Issue by knownasilya** [stefanpenner/ember-state-services#42]
Basically every instance of a model of the same type returns true for `weakmap.has(model)`. Makes it impossible to use Ember Data models as the key, e.g. `data: stateFor('model-options', 'model')`.

----

Edit: Failing test is in #43

**Comment by stefanpenner** [comment]
can you provide a failing test

**Comment by knownasilya** [comment]
@thoov any initial thoughts?

**Comment by stefanpenner** [comment]
I had a guess, it's possible the state WeakMap is accidentally being installed in the inherited map rather then created an `own` map for the given object.

**Comment by thoov** [comment]
@knownasilya @stefanpenner There is a problem with the test that you provided in which:

```js
var modelA = this.subject({
  name: 'john'
});

var modelB = this.subject({
  name: 'jane'
});

// modelA === modelB is true
// and internally the stateFor computed property doesnt detect that the dependency key has changed.
```

I then created a sample app which used ember data models and everything worked correctly. Here are the files that I added to the dummy folder (https://gist.github.com/thoov/60c237a32c967546bc1b). @knownasilya can you add these files and see if it works for you?

After you add them can you do the following: Visit /baz and click on the "Foo" link. Then click on the "Baz" link. (This creates a model inside of the store). Do this a few times until you see a few "A different model" links on the page. Click on one of the links and you will see a text area. Fill it in with something and then click the "Baz" link. After that click on a different "model link" and do the same thing. You will notice that the state is persisted for the same model and changes to a blank state for new models.

**Comment by knownasilya** [comment]
@thoov are you saying that `this.subject` doesn't create a new model? If so, I can update to use the store directly to create the models.

**Comment by knownasilya** [comment]
You were right.

**Comment by stefanpenner** [comment]
> @thoov are you saying that this.subject doesn't create a new model?

ya, in a test it is memoized.
