### ISSUE TITLE
Cut a new release

### ISSUE THREAD

**Issue by mike-north** [stefanpenner/ember-state-services#62]
Some of @thoov's recent ember 2.8 compatibility stuff isn't in the latest npm release.

Workaround: refer to a SHA in your package.json
```js
"ember-state-services": "stefanpenner/ember-state-services#02dcb9c50a6cdd22e5e2b782eb621474917a6ad9",
```

**Comment by stefanpenner** [comment]
@mike-north good catch (on crappy internet at the moment) you now have npm owner  and git admin. Do you have some cycles to cut the appropriate release?

**Comment by mike-north** [comment]
@stefanpenner v3.2 cut, tagged and published

**Comment by thoov** [comment]
@mike-north thanks
