### ISSUE TITLE
Resolving the state key to a primitive value

### ISSUE THREAD

**Issue by oakerele** [stefanpenner/ember-state-services#71]
Rookie question: I'm trying to save the state of texts in a message box, but when I do this `
      this.get('email').setProperties(this.get('messageData'));`, I get a TypeError `The state key must resolve to a non primitive value`. 

I understand that the key `email` needs to be an object for here `data: stateFor('message', 'email')`,  but the email is actually a String which doesn't work here and for reasons unknown to me, I can't seem to get this. Is there something I'm missing (probably very simple)?

Thanks

**Comment by thoov** [comment]
Hey @oakerele, would you be able to paste your whole file here (or if you could create a twiddle) so I could take a look?

As you pointed out if you are getting the error of: `The state key must resolve to a non primitive value.` That means the `email` property is not defined as an object or function within the current context. Most likely the solution will have to be to transform `email` from something  an object that might look like:

```js
email: {
  address: 'foo@bar.com'
}
```
but I would need to see your full example to better understand what is going on.

**Comment by oakerele** [comment]
Thanks a lot! I was just strong headed to think that I could do it another way that isn't like what you said above. It works now!
