### ISSUE TITLE
Deprecate old npm `services-sessions`

### ISSUE THREAD

**Issue by jayphelps** [stefanpenner/ember-state-services#9]
I don't have access to the `services-sessions` npm, but I published `ember-state-services` and added @stefanpenner as another owner since AFAIK there's no *real* way to rename.

Now we just need to deprecate the old one. Something like
```shell
$ npm deprecate service-sessions@"0.0.1" "Project has been renamed to ember-state-services."
```

Feel free to just add me to the old npm package and I'll handle adding a README deprecation notice and deprecate the registry entry.

```shell
npm owner add jayphelps service-sessions
```

**Comment by stefanpenner** [comment]
updated!
